### ISSUE TITLE
Calendar item return only one meeting in the future

### ISSUE THREAD

**Issue by Chouffy** [sharkoz/keypirinha-outlook_calendar#1]
Hi,

When I access the "Calendar" item, I only see one item from the future:
![image](https://user-images.githubusercontent.com/9288966/113142806-9cfce300-922b-11eb-9b08-cdfc74297b44.png)
Current date: 31 march 2021

My current configuration:
* Plugin installed through PackageManager, with Keypirinha restarted
* Outlook for Microsoft 365 x64 - version 2008
* Windows 10 x64 - version 20H2
* Windows date and time in custom format: yy.mm.dd hh:mm

Let me know if I can help you further to debug this.
Thanks!

**Comment by sharkoz** [comment]
Hi,

By default the plugin only shows only events occuring today. Would this explain what you see ? Have you tried it another day ?
I will see if I can make this a setting to allow for viewing events for more days.

**Comment by sharkoz** [comment]
OK well I took the time to check it again and I am pretty sure I found the bug that you had.

Can you try on the latest version ? You can update the plugin from the package manager directly. To make sure you are on the latest version, try to type something while looking at your events (or event in your case), it should filter the list. If it doesn't, you are not on the latest version. You can try to remove the plugin and install it again.

I'll close the issue for now.

**Comment by Chouffy** [comment]
Hi,
Indeed it's solved on the latest version, thanks a bunch!
