### ISSUE TITLE
Does not support ISO 8601 (yyyy-mm-dd) format

### ISSUE THREAD

**Issue by egabrum** [sharkoz/keypirinha-outlook_calendar#2]
To reproduce:
1) Set date to May 4th.
2) Enter event on April 6th
3) Enter event on May 5th
4) On W10, set Short date format to yyyy-mm-dd, (ISO 8601) to avoid the dd/mm/yy - mm/dd/yy nonsense :-) 
This is in Settings - Time & Language - Region - Change data formats
5) Open the Calendar plugin  in Keypirinha.

ISSUE: All the events since April 5th (in the past) are shown, possibly filling the list and obfuscating events in the future.

_Everything, everybody_ should support ISO 8601 ! 😆

Great plugin, btw.

**Comment by sharkoz** [comment]
Thanks for your feedback
Your case is tricky as I did not find how to properly set the shortdate format to match the one set in win10
locale.setlocale(locale.LC_ALL, '') gets your global locale but it doesn't take into account your use case.

So for now I added a configuration option to change the format of the date sent to Outlook to filter events.
So if you update to the latest version, you can configure the date_format option in the config of the plugin to : 
```
[main]
date_format = '%Y-%m-%d'`
```
It should work for you.

I'll close the issue for now, tell me if this doesn't work.

**Comment by egabrum** [comment]
That was fast...
Works like a charm!
Thanks
